### ISSUE TITLE
Using the parse-routes.py script on Windows

### ISSUE THREAD

**Issue by bmffb** [darauble/Locus-Map-DIY#1]
I have some trouble to run your python script for the conversion of route relations on a Windows PC.  What I have done so far:
1. installed Miniconda for win64
2. ran `conda install -c conda-forge osmium-tool` (according to #https://github.com/osmcode/osmium-tool/issues/59
3. checked in the Anaconda Prompt if osmium is installed by `osmium --version` and got
   osmium version 1.14.0
   libosmium version 2.17.1
   Supported PBF compression types: none zlib lz4
   Copyright (C) 2013-2022  Jochen Topf <jochen@topf.org>
   License: GNU GENERAL PUBLIC LICENSE Version 3 <https://gnu.org/licenses/gpl.html>.
   This is free software: you are free to change and redistribute it.
   There is NO WARRANTY, to the extent permitted by law.
4. try to run your script in the Anaconda Prompt using `parse_routes.py $test.osm.pbf $test_routes.osm` and get
   Traceback (most recent call last):
     File "C:\Users\bernard\parse_routes.py", line 5, in <module>
       import osmium
   ModuleNotFoundError: No module named 'osmium'

What do I do wrong? Is there a way to run your script on Windows?
Any help is appreciated.

**Comment by darauble** [comment]
I have a suspicion you didn't install `PyOsmium`, which is the Python library. I installed it using `pip3`.

**Comment by bmffb** [comment]
Thanks. You are right. The first step is solved.
I have successfully installed PyOsmium using `pip install osmium`.

Now, when I try to run your script in a Windows terminal by `python parse-routes.py $test.osm.pbf $test_routes.osm` (in the folder containing the data file "test.osm.pbf") I get the following error:
   Reading header...
   Traceback (most recent call last):
     File "D:\KARTENBAU\parse-routes.py", line 130, in <module>
       reader = osmium.io.Reader(file_name)
   RuntimeError: Open failed for '$test.osm.pbf': Das System kann die angegebene Datei nicht finden.

Sorry, I am running on a German Windows. So the error means "can not find the file". 
Is this the wrong format/syntax for the run command?

**Comment by darauble** [comment]
Do your file names really contain "$"?

2022 m. lapkr. 15 d., an 19:23, bmffb ***@***.***> rašė:

**Comment by bmffb** [comment]
Stupid mistake/misunderstanding. I simply copied the line out of your shell script and thought the "$" is a necessary part. I guess it is just the syntax of a variable.
When I run now `python parse-routes.py test.osm.pbf test_routes.osm` everything runs smoothly. I get a .osm file containing the expected routes.
Thanks.

**Comment by darauble** [comment]
Cool! Yes, the dollar sign is a variable in Linux shell. In windows, I
think, percentage characters are used. Good luck!

2022 m. lapkr. 15 d., an 19:33, bmffb ***@***.***> rašė:

**Comment by bmffb** [comment]
Just some documentation for _dummies_.
This is what I need on a Windows 11 64bit machine:

1. A running installation of [**Python 3**](https://www.python.org/ftp/python/3.11.0/python-3.11.0-amd64.exe) 
2. Install **PyOsmium** by running `pip install osmium` in a terminal window
3. Check osmium installation in Python (in a terminal window, with `enter `after each command)
    `python`
   ` help()`
    `modules`
The osmium module should show up in the list.
4. Then one can run in a terminal window: `python parse-routes.py test.osm.pbf test_routes.osm` where 'test.osm.pbf is the osm-data file containing route data and 'test_routes.osm' is the output file containing the extracted/copied route information.

**Comment by bmffb** [comment]
Thanks again.
